### PR TITLE
update clickhouse-rs

### PR DESCRIPTION
**Pull request by suharev7**
This PR applies a new API to improve the performance of `block_to_df` function.

### CODE REVIEW

**Comment by jspeis** [comment]
@suharev7 wow suharev, thank you so much for submitting this PR. We'll just run some additional internal integration tests to ensure things on our end (we haven't fully migrated these to the CI yet, though that is on our to do list). Hope to have this merged in soon. Thanks again!

**Comment by jspeis** [comment]
Looks good to me from my checks. @MarcioPorto when you have the chance if you could also just run a quick check on OEC, if that's good then we should be ok to merge.

**Comment by MarcioPorto** [comment]
@jspeis Looks good on OEC!

**Comment by jspeis** [comment]
Merged! Thanks again @suharev7!

**Pull request merged**
